config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"
  resources :doctor_profile do
    collection do
      get 'show_spec'
    end
  end
  resources :patient_profile




  resources :doctor_profile do
    collection do
      get 'show_spec'
    end
  end

  resources :patient_profile do
    collection do
      get 'get_items'
    end
  end

  resources :visit_types
  resources :schedules

  devise_for :users, controllers: { registrations: 'user/registrations',
                                    sessions: 'user/sessions',
                                    passwords: 'user/passwords',
                                    confirmations: 'user/confirmations'}
  resources :visits, except: [:edit, :update] do
    member do
      get 'choose_date'
    end
  end

  match '/admin/*path', to: 'admin#index', via: :all


  get 'account' => 'users#show'
  get '/slots' => 'visits#slots'
  get '/manager' => 'users#manage'
  get '/manager/patients' => 'users#get_patients'
  get '/manager/doctors' => 'users#get_doctors'
  get '/users' => 'users#index'
  get '/users_to_react_form' => 'users#users_to_react_form'
  post 'send_tel' => 'home#send_numb'
  get '/users_by_id' => 'users#find_doctor_by_id'
  get 'choose_date' => 'visits#choose_date'
  post 'rails/active_storage/direct_uploads', to: 'direct_uploads#create'
  get 'departments' => 'doctor_profile#departments'
end

app/models/user.rb
class User < ApplicationRecord
  has_one :patient_profile, dependent: :destroy
  has_one :doctor_profile, dependent: :destroy
  has_many :schedules, dependent: :destroy

  has_many :visits, foreign_key: "created_by_id", dependent: :nullify

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  validates :name, :surname, presence: true

  enum role: %i(admin manager doctor patient)
end

app/controllers/User/confirmations_controller.rb
# frozen_string_literal: true

class User::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/User/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class User::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/User/passwords_controller.rb
# frozen_string_literal: true

class User::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  def new
    super
  end

  # POST /resource/password
  def create
    super
  end

  # GET /resource/password/edit?reset_password_token=abcdef
  def edit
    super
  end

  # PUT /resource/password
  def update
    super
  end

  protected

  def after_resetting_password_path_for(resource)
    super(resource)
  end

  # The path used after sending reset password instructions
  def after_sending_reset_password_instructions_path_for(resource_name)
    super(resource_name)
  end
end

app/controllers/User/registrations_controller.rb
# frozen_string_literal: true

class User::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  # GET /resource/sign_up
  def new
    super
  end

  # POST /resource
  def create
    super
  end

  # GET /resource/edit
  def edit
    super
  end

  # PUT /resource
  def update
    super
  end

  # DELETE /resource
  def destroy
    # if current_user.role == 'patient'
    #   patient_visits = Visit.where(patient_id: current_user.id)
    #   puts "============================================"
    #   puts patient_visits
    #   patient_visits.each do |visit|
    #     puts visit.patient_id
    #     visit.patient_id = nil
    #     puts visit.patient_id
    #     visit.save!
    #   end
    # elsif current_user.role == 'doctor'
    #   doctor_visits = Visit.where(doctor_id: current_user.id)
    #   doctor_visits.each do |visit|
    #     visit.doctor_id = nil
    #     visit.save
    #   end
    # end
    current_user.is_active = false
    current_user.save
    sign_out current_user
    flash[:notice] = "Your account was successfully deleted."
    redirect_to root_path
    # super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :surname, :phone_number])
  end

  # If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :surname, :phone_number])
  end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  # The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/User/sessions_controller.rb
# frozen_string_literal: true

class User::SessionsController < Devise::SessionsController
  before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  def new
    super
  end

  # POST /resource/sign_in
  def create
    super
  end

  # DELETE /resource/sign_out
  def destroy
    super
  end

  protected

  # If you have extra params to permit, append them to the sanitizer.
  def configure_sign_in_params
    devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  end
end

app/controllers/User/unlocks_controller.rb
# frozen_string_literal: true

class User::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  # after_action :verify_authorized
  after_action :verify_policy_scoped, only: :index

  def index
    @users = policy_scope(User)
    authorize @users, policy_class: UserPolicy
  end

  def show
    @user = current_user
    authorize @user, policy_class: UserPolicy
  end

  def users_to_react_form
    @users = User.all
    authorize @users, policy_class: UserPolicy
    render json: @users
  end

  def find_doctor_by_id
    @doctor = User.find(params[:id])
    doctor_card = {
      name: @doctor.name,
      surname: @doctor.surname,
      specialization: @doctor.doctor_profile.specialization,
      description: @doctor.doctor_profile.description
    }
    authorize @doctor, policy_class: UserPolicy
    render json: doctor_card
  end

  def manage
    authorize current_user, policy_class: UserPolicy
  end

  def get_patients
    @patients = User.where(role: 'patient')
    authorize @patients, policy_class: UserPolicy
  end

  def get_doctors
    @doctors = User.where(role: 'doctor')
    authorize @doctors
  end

  private

  def user_params
    params.require(:user).permit(:id)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/get_doctors.html.erb
<h1><%= t 'manager_bar.doctors' %>:</h1>
<table class="table">
  <thead>
  <tr>
    <th><%= t 'activerecord.attributes.users.name' %></th>
    <th><%= t 'activerecord.attributes.users.surname' %></th>
    <th><%= t 'activerecord.attributes.users.email' %></th>
    <th><%= t 'activerecord.attributes.users.phone_number' %></th>
    <th><%= t 'activerecord.attributes.users.is_active' %></th>
    <th><%= t 'activerecord.attributes.users.registration_date' %></th>
  </tr>
  </thead>

  <tbody>
  <% @doctors.each do |doctor| %>
    <tr>
      <td><%= doctor.name %></td>
      <td><%= doctor.surname %></td>
      <td><%= doctor.email %></td>
      <td><%= doctor.phone_number %></td>
      <td><%= doctor.is_active %></td>
      <td><%= doctor.created_at.strftime("%Y-%m-%d") %></td>

      <!--        <td><%#= link_to 'Show', doctor %></td>-->
      <!--        <td><%#= link_to 'Delete', doctor, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
    </tr>
  <% end %>
  </tbody>
</table>


<%#= link_to 'New Doctor', new_user_path %>

app/views/users/get_patients.html.erb
<h1><%= t 'manager_bar.patients' %>:</h1>
  <table class="table">
    <thead>
    <tr>
      <th><%= t 'activerecord.attributes.users.name' %></th>
      <th><%= t 'activerecord.attributes.users.surname' %></th>
      <th><%= t 'activerecord.attributes.users.email' %></th>
      <th><%= t 'activerecord.attributes.users.phone_number' %></th>
      <th><%= t 'activerecord.attributes.users.is_active' %></th>
      <th><%= t 'activerecord.attributes.users.registration_date' %></th>
    </tr>
    </thead>

    <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.surname %></td>
        <td><%= patient.email %></td>
        <td><%= patient.phone_number %></td>
        <td><%= patient.is_active %></td>
        <td><%= patient.created_at.strftime("%Y-%m-%d") %></td>

<!--        <td><%#= link_to 'Show', patient %></td>-->
<!--        <td><%#= link_to 'Delete', patient, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
    </tbody>
  </table>


<%#= link_to 'New Patient', new_user_path %>

app/views/users/index.html.erb
<h1>Users:</h1>
<% unless @users.empty? %>
  <table class="table">
    <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Email</th>
      <th>Phone number</th>
      <th>Active</th>
      <th>Registration date</th>
    </tr>
    </thead>

    <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= user.surname %></td>
        <td><%= user.email %></td>
        <td><%= user.phone_number %></td>
        <td><%= user.is_active %></td>
        <td><%= user.created_at %></td>

        <!--        <td><%#= link_to 'Show', user %></td>-->
        <!--        <td><%#= link_to 'Delete', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>

app/views/users/manage.html.erb
<body>
  <h1> Wellcome to manager page! </h1>
</body>

app/views/users/show.html.erb
<section class="devise">
  <div class="container">
    <h2><b><%= "#{@user.name} #{@user.surname}" %></b></h2>
    <div class="container">
      <p>
        <strong><%= t 'activerecord.attributes.users.email' %>:</strong>
        <%= @user.email %>
      </p>

      <p>
        <strong><%= t 'activerecord.attributes.users.phone_number' %>:</strong>
        <%= @user.phone_number %>
      </p>
      <span class="psw"><%= link_to "#{ t 'account.edit_account' }", edit_user_registration_path %></span>
      <% if @user.role == 'patient' %>
        <div>
          <span class="psw"><%= link_to "#{ t 'account.patient_card' }" %></span>
        </div>
      <% end %>
      <% if @user.role == 'doctor' %>
        <div>
          <span class="psw"><%= link_to "#{ t 'account.doctor_profile' }" %></span>
        </div>
        <div>
          <span class="psw"><%= link_to "#{ t 'account.my_schedules' }", schedules_path %></span>
        </div>
      <% end %>
      <% if @user.role == 'doctor' or @user.role == 'patient' %>
        <div>
          <span class="psw"><%= link_to "#{ t 'account.my_visits' }", visits_path %></span>
        </div>
        <% end %>
      <% if @user.role == 'manager' %>
          <div>
            <span class="psw"><%= link_to "#{ 'Manager Dashboard' }", manager_path %></span>
          </div>
      <% end %>
      <% if @user && @user.role == 'admin' %>
        <div>
          <a href="/admin/index">Dashboard</a>
        </div>
        <div>
          <a href="/patient_profile">Patient profile</a>
        </div>
      <% end %>
    </div>
  </div>
</section>