config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"
  resources :doctor_profile do
    collection do
      get 'show_spec'
    end
  end
  resources :patient_profile




  resources :doctor_profile do
    collection do
      get 'show_spec'
    end
  end

  resources :patient_profile do
    collection do
      get 'get_items'
    end
  end

  resources :visit_types
  resources :schedules

  devise_for :users, controllers: { registrations: 'user/registrations',
                                    sessions: 'user/sessions',
                                    passwords: 'user/passwords',
                                    confirmations: 'user/confirmations'}
  resources :visits, except: [:edit, :update] do
    member do
      get 'choose_date'
    end
  end

  match '/admin/*path', to: 'admin#index', via: :all


  get 'account' => 'users#show'
  get '/slots' => 'visits#slots'
  get '/manager' => 'users#manage'
  get '/manager/patients' => 'users#get_patients'
  get '/manager/doctors' => 'users#get_doctors'
  get '/users' => 'users#index'
  get '/users_to_react_form' => 'users#users_to_react_form'
  post 'send_tel' => 'home#send_numb'
  get '/users_by_id' => 'users#find_doctor_by_id'
  get 'choose_date' => 'visits#choose_date'
  post 'rails/active_storage/direct_uploads', to: 'direct_uploads#create'
  get 'departments' => 'doctor_profile#departments'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :user
  belongs_to :visit_type
  enum day: { Monday: 1, Tuesday: 2, Wednesday: 3, Thursday: 4, Friday: 5, Saturday: 6, Sunday: 7 }

  validates :user, :visit_type, :day, :start_time, :end_time, :start_date, :end_date, presence: true
  validates_with ScheduleValidator
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  after_action :verify_authorized
  after_action :verify_policy_scoped, only: :index

  # GET /visits
  # GET /visits.json
  def index
    @schedules = policy_scope(Schedule)
    authorize @schedules
  end

  # GET /visits/1
  # GET /visits/1.json
  def show
    @schedule = policy_scope(Schedule).find(params[:id])
  end

  # GET /visits/new
  def new
    @schedule = Schedule.new
    authorize @schedule
  end


  # GET /visits/1/edit
  def edit

  end

  # POST /visits
  # POST /visits.json
  def create
    @schedule = Schedule.new(schedule_params)
    authorize @schedule

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to @schedule, notice: 'Schedule was successfully created.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render :new }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visits/1
  # PATCH/PUT /visits/1.json
  def update
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to @schedule, notice: 'Schedule was successfully updated.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render :edit }
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visits/1
  # DELETE /visits/1.json
  def destroy
    if @schedule.destroy
      respond_to do |format|
        format.html { redirect_to schedules_url, notice: 'Schedule was successfully canceled.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to schedules_path, alert: "Schedule can't be canceled. #{@schedule.errors[:base][-1]}"}
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_schedule
    @schedule = Schedule.find(params[:id])
    authorize @schedule
  end

  # Only allow a list of trusted parameters through.
  def schedule_params
    params.require(:schedule).permit(:user_id, :day, :start_time, :end_time, :visit_type_id, :start_date, :end_date)
  end
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this visit from being saved:</h2>

      <ul>
        <% schedule.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t 'activerecord.attributes.schedules.doctor' %>
    <%= form.select :user_id, User.where(:role => 'doctor').order(:surname).map{ |user| ["#{user.surname} #{user.name}", user.id]}%>
  </div>

  <div class="field">
    <%= form.label t 'activerecord.attributes.schedules.day' %>
    <%= form.select :day, Schedule.days.keys.to_a.map{ |day| [( t "days.#{day.downcase}"), day]} %>
  </div>

  <div class="field">
    <%= form.label t 'activerecord.attributes.schedules.start_time' %>
    <%= form.time_select :start_time, minute_step: 30 %>
  </div>

  <div class="field">
    <%= form.label t 'activerecord.attributes.schedules.end_time' %>
    <%= form.time_select :end_time, minute_step: 30 %>
  </div>

  <div class="field">
    <%= form.label t 'activerecord.attributes.schedules.start_date' %>
    <%= form.date_select :start_date %>
  </div>

  <div class="field">
    <%= form.label t 'activerecord.attributes.schedules.end_date' %>
    <%= form.date_select :end_date %>
  </div>

  <div class="field">
    <%= form.label t 'activerecord.attributes.schedules.visit_type' %>
    <%= form.select :visit_type_id, VisitType.all.order(:length).map{ |vt| [ (t "visit_types.#{ vt.name }"), vt.id]}%>
  </div>

  <div class="actions">
    <%= form.submit t 'activerecord.attributes.schedules.create_schedule' %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1><%= t 'activerecord.attributes.schedules.edit_schedule' %></h1>

<%= render 'form', schedule: @schedule %>

<%= link_to (t 'records.edit'), @schedule %>
<%= link_to (t 'records.back'), schedule_path %>

app/views/schedules/index.html.erb
<h1><%= t 'activerecord.attributes.schedules.schedules' %>:</h1>
<% if @schedules.empty? %>
  <h4><%= t 'activerecord.attributes.schedules.no_schedules_message' %>:</h4>
<% end %>
<% unless @schedules.empty? %>
<table class="table">
  <thead>
    <tr>
      <th><%= t 'activerecord.attributes.schedules.doctor' %></th>
      <th><%= t 'activerecord.attributes.schedules.day' %></th>
      <th><%= t 'activerecord.attributes.schedules.start_time' %></th>
      <th><%= t 'activerecord.attributes.schedules.end_time' %></th>
      <th><%= t 'activerecord.attributes.schedules.start_date' %></th>
      <th><%= t 'activerecord.attributes.schedules.end_date' %></th>
      <th><%= t 'activerecord.attributes.schedules.visit_type' %></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <% dt_format = "%H:%M" %>
        <td><%= "#{schedule.user.name} #{schedule.user.surname}" %></td>
        <td><%= t "days.#{schedule.day.downcase}" %></td>
        <td><%= schedule.start_time.strftime(dt_format) %></td>
        <td><%= schedule.end_time.strftime(dt_format) %></td>
        <td><%= schedule.start_date %></td>
        <td><%= schedule.end_date %></td>
        <td><%= t "visit_types.#{schedule.visit_type.name}" %></td>

        <td><%= link_to "#{ t 'records.show'}", schedule %></td>
        <td><%= link_to "#{ t 'records.edit'}", edit_schedule_path(schedule) %></td>
        <td><%= link_to "#{ t 'records.delete'}", schedule, method: :delete, data: { confirm: (t 'account.are_you_sure') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>


<%= link_to "#{ t 'activerecord.attributes.schedules.new_schedule'}", new_schedule_path %>

app/views/schedules/new.html.erb
<h1><%= t 'activerecord.attributes.schedules.new_schedule' %>:</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p>
  <strong><%= t 'activerecord.attributes.schedules.doctor' %>:</strong>
  <%= @schedule.user.name %> <%= @schedule.user.surname %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.schedules.day' %>:</strong>
  <%= t "days.#{@schedule.day.downcase}" %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.schedules.start_time' %>:</strong>
  <%= @schedule.start_time.strftime("%H:%M") %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.schedules.end_time' %>:</strong>
  <%= @schedule.end_time.strftime("%H:%M") %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.schedules.start_date' %>:</strong>
  <%= @schedule.start_date.strftime("%Y-%m-%d") %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.schedules.end_date' %>:</strong>
  <%= @schedule.end_date.strftime("%Y-%m-%d") %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.schedules.visit_type' %>:</strong>
  <%= t "visit_types.#{@schedule.visit_type.name}" %> <%= @schedule.visit_type.length %> <%= t 'activerecord.attributes.visit_types.minutes' %>
</p>

<%= link_to (t 'records.back'), schedules_path %> |
<%= link_to (t 'records.edit'), edit_schedule_path %> |
<%= link_to (t 'records.delete'), @schedule, method: :delete, data: { confirm: (t 'account.are_you_sure') } %>