config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"
  resources :doctor_profile do
    collection do
      get 'show_spec'
    end
  end
  resources :patient_profile




  resources :doctor_profile do
    collection do
      get 'show_spec'
    end
  end

  resources :patient_profile do
    collection do
      get 'get_items'
    end
  end

  resources :visit_types
  resources :schedules

  devise_for :users, controllers: { registrations: 'user/registrations',
                                    sessions: 'user/sessions',
                                    passwords: 'user/passwords',
                                    confirmations: 'user/confirmations'}
  resources :visits, except: [:edit, :update] do
    member do
      get 'choose_date'
    end
  end

  match '/admin/*path', to: 'admin#index', via: :all


  get 'account' => 'users#show'
  get '/slots' => 'visits#slots'
  get '/manager' => 'users#manage'
  get '/manager/patients' => 'users#get_patients'
  get '/manager/doctors' => 'users#get_doctors'
  get '/users' => 'users#index'
  get '/users_to_react_form' => 'users#users_to_react_form'
  post 'send_tel' => 'home#send_numb'
  get '/users_by_id' => 'users#find_doctor_by_id'
  get 'choose_date' => 'visits#choose_date'
  post 'rails/active_storage/direct_uploads', to: 'direct_uploads#create'
  get 'departments' => 'doctor_profile#departments'
end

app/views/shared/_flash.html.erb
<%# flash.each do |key, value| %>
<!--  <div class="container">-->
<!--    <div class="alert <%#= key == 'notice' ? 'alert-primary' : 'alert-danger' %>" role="alert">-->
      <%#= value %>
<!--    </div>-->
<!--  </div>-->
  <%= react_component("Devise/Notification", { flash: flash }) %>
<%# end %>

app/views/shared/_manager_bar.html.erb
<div class="sidebar">
  <%= link_to (t 'manager_bar.patients'), manager_patients_path %>
  <%= link_to (t 'manager_bar.doctors'), manager_doctors_path %>
  <%= link_to (t 'manager_bar.visits'), visits_path %>
  <%= link_to (t 'manager_bar.visit_types'), visit_types_path %>
  <%= link_to (t 'manager_bar.schedules'), schedules_path %>
</div>

app/views/shared/_navigation.html.erb
<!--<header class="main" xmlns="http://www.w3.org/1999/html">-->
<!--  <div class="topnav">-->
    <%#= link_to (t "nav_bar.main"), root_path, class: "active" %>
    <%#= link_to (t "nav_bar.news"), root_path %>
    <%#= link_to (t "nav_bar.contacts"), root_path %>

<!--    <div class="dropdown">-->
<!--      <button class="dropbtn">Departments-->
<!--        <i class="fa fa-caret-down"></i>-->
<!--      </button>-->
<!--      <div class="dropdown-content">-->
        <%# doctor_departments.each do |d| %>
          <%#= link_to d[0], show_spec_doctor_profile_index_path(:position => d[1])  %>
        <%# end %>
<!--      </div>-->
<!--    </div>-->

    <%# if current_user && current_user.role == 'admin' %>
<!--      <a href="/admin/index">Admin</a>-->
<!--      <a href="/patient_profile">Patient profile</a>-->
    <%# end %>

<!--    <div class="topnav-right">-->
<!--      <div class="dropdown">-->
<!--        <button class="dropbtn"><%#= locale.upcase %>-->
<!--          <i class="fa fa-caret-down"></i>-->
<!--        </button>-->
<!--        <div class="dropdown-content">-->
          <%#= link_to "EN", url_for(locale: :en) %>
          <%#= link_to "RU", url_for(locale: :ru) %>
          <%#= link_to "UK", url_for(locale: :uk) %>
<!--        </div>-->
<!--      </div>-->
      <%# if current_user %>
        <%#= link_to "#{current_user.name} #{current_user.surname}", account_path %>
        <%#= link_to "#{t "nav_bar.log_out"}", destroy_user_session_path, method: :delete %>
      <%# else %>
        <%#= link_to "#{t "nav_bar.log_in"}", new_user_session_path %>
        <%#= link_to "#{t "nav_bar.sign_up"}", new_user_registration_path %>
      <%# end %>
<!--    </div>-->
<!--  </div>-->
<!--</header>-->

<%= react_component("NavBar/NavBar", { locale: locale, root_path: root_path, departments: doctor_departments,
                                       user: current_user, logout_path: destroy_user_session_path,
                                       login_path: new_user_session_path, account_path: account_path,
                                       registration_path: new_user_registration_path,
                                       spec_path: show_spec_doctor_profile_index_path}) %>