config/routes.rb
Rails.application.routes.draw do
  
  root to: "home#index"
  resources :doctor_profile do
    collection do
      get 'show_spec'
    end
  end
  resources :patient_profile




  resources :doctor_profile do
    collection do
      get 'show_spec'
    end
  end

  resources :patient_profile do
    collection do
      get 'get_items'
    end
  end

  resources :visit_types
  resources :schedules

  devise_for :users, controllers: { registrations: 'user/registrations',
                                    sessions: 'user/sessions',
                                    passwords: 'user/passwords',
                                    confirmations: 'user/confirmations'}
  resources :visits, except: [:edit, :update] do
    member do
      get 'choose_date'
    end
  end

  match '/admin/*path', to: 'admin#index', via: :all


  get 'account' => 'users#show'
  get '/slots' => 'visits#slots'
  get '/manager' => 'users#manage'
  get '/manager/patients' => 'users#get_patients'
  get '/manager/doctors' => 'users#get_doctors'
  get '/users' => 'users#index'
  get '/users_to_react_form' => 'users#users_to_react_form'
  post 'send_tel' => 'home#send_numb'
  get '/users_by_id' => 'users#find_doctor_by_id'
  get 'choose_date' => 'visits#choose_date'
  post 'rails/active_storage/direct_uploads', to: 'direct_uploads#create'
  get 'departments' => 'doctor_profile#departments'
end

app/controllers/visit_types_controller.rb
class VisitTypesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_visit_type, only: [:show, :edit, :update, :destroy]
  # GET /doctors
  # GET /doctors.json
  def index
    @visit_types = VisitType.order(:name)
    authorize @visit_types
  end

  # GET /doctors/1
  # GET /doctors/1.json
  def show

  end

  # GET /doctors/new
  def new
    @visit_type = VisitType.new
    authorize @visit_type
  end

  # GET /doctors/1/edit
  def edit

  end

  # POST /doctors
  # POST /doctors.json
  def create
    @visit_type = VisitType.new(visit_type_params)
    authorize @visit_type
    respond_to do |format|
        if @visit_type.save
          format.html { redirect_to @visit_type, notice: 'Visit type was successfully created.' }
          format.json { render :show, status: :created, location: @visit_type }
        else
          format.html { render :new }
          format.json { render json: @visit_type.errors, status: :unprocessable_entity }
        end
      end
  end

  # PATCH/PUT /doctors/1
  # PATCH/PUT /doctors/1.json
  def update
    respond_to do |format|
      if @visit_type.update(visit_type_params)
        format.html { redirect_to @visit_type, notice: 'Visit type was successfully updated.' }
        format.json { render :show, status: :ok, location: @visit_type }
      else
        format.html { render :edit }
        format.json { render json: @visit_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /doctors/1
  # DELETE /doctors/1.json
  def destroy
    if @visit_type.destroy
      respond_to do |format|
        format.html { redirect_to visit_types_url, notice: 'Visit type was successfully deleted.' }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        format.html { redirect_to visit_types_path, alert: "Visit type can't be deleted. #{@dvisit_type.errors[:base][-1]}"}
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_visit_type
    @visit_type = VisitType.find(params[:id])
    authorize @visit_type
  end

  # Only allow a list of trusted parameters through.
  def visit_type_params
    params.require(:visit_type).permit(:name, :description, :length)
  end
end

app/helpers/visit_types_helper.rb
module VisitTypesHelper
end

app/views/visit_types/_form.html.erb
<%= form_with(model: visit_type, local: true) do |form| %>
  <% if visit_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visit_type.errors.count, "error") %> prohibited this visit type from being saved:</h2>

      <ul>
        <% visit_type.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label t 'activerecord.attributes.visit_types.name' %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label t 'activerecord.attributes.visit_types.description' %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label t 'activerecord.attributes.visit_types.duration' %>
    <%= form.text_field :length %>
  </div>

  <div class="actions">
    <%= form.submit t 'activerecord.attributes.visit_types.create_visit_type' %>
  </div>
<% end %>

app/views/visit_types/edit.html.erb
<h1><%= t 'activerecord.attributes.visit_types.edit_visit_type' %></h1>

<%= render 'form', visit_type: @visit_type %>

<%= link_to (t 'records.show'), @visit_type %>
<%= link_to (t 'records.back'), visit_type_path %>

app/views/visit_types/index.html.erb
<h1><%= t 'activerecord.attributes.visit_types.visit_types' %></h1>
<table class="table">
    <tfoot>
    <tr>
        <td colspan="3">
            <%= link_to (t 'activerecord.attributes.visit_types.new_visit_type'), new_visit_type_path %>
        </td>
    </tr>
    </tfoot>
    <tbody>
    <% @visit_types.each do |vt| %>
    <tr>
        <td class="description">
            <h2><%= t "visit_types.#{vt.name}" %></h2>
            <h4>
              <%= t "visit_types.#{vt.description}" %>
            </h4>
            <h4>
              <%= t 'activerecord.attributes.visit_types.duration' %>: <%= vt.length %> <%= t 'activerecord.attributes.visit_types.minutes' %>
            </h4>
        </td>
        <td class="actions">
            <ul>
                <li><%= link_to (t 'records.show'), vt %></li>
                <li><%= link_to (t 'records.edit'), edit_visit_type_path(vt) %></li>
                <li>
                    <%= link_to (t 'records.delete'),
                                vt,
                                method: :delete,
                                data: { confirm: (t 'account.are_you_sure') } %>
                </li>
            </ul>
        </td>
    </tr>
    <% end %>
    </tbody>
</table>

app/views/visit_types/new.html.erb
<h1><%= t 'activerecord.attributes.visit_types.new_visit_type' %></h1>

<%= render 'form', visit_type: @visit_type %>

<%= link_to (t 'records.back'), visit_types_path %>

app/views/visit_types/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong><%= t 'activerecord.attributes.visit_types.name' %>:</strong>
  <%= @visit_type.name %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.visit_types.description' %>:</strong>
  <%= @visit_type.description %>
</p>

<p>
  <strong><%= t 'activerecord.attributes.visit_types.duration' %>:</strong>
  <%= @visit_type.length %>
</p>

<%= link_to (t 'records.edit'), edit_visit_type_path(@visit_type) %> |
<%= link_to (t 'records.back'), visit_types_path %>